import os
import json
import hashlib
from pathlib import Path
from web3 import Web3
from dotenv import load_dotenv

_this_dir = Path(__file__).resolve().parent
for _parent in [_this_dir, _this_dir.parent, _this_dir.parent.parent]:
    _env_path = _parent / ".env"
    if _env_path.exists():
        load_dotenv(_env_path, override=True)
        break
else:
    load_dotenv(override=True)  # Fallback: search from cwd

def compress_state_to_hash(state_vector) -> bytes:
    deterministic_repr = ",".join([f"{float(v):.4f}" for v in state_vector])
    hasher = hashlib.sha256()
    hasher.update(deterministic_repr.encode("utf-8"))
    return hasher.digest()

class BlockchainLogger:
    def __init__(self):
        rpc_url = os.environ.get("RPC_URL", "http://127.0.0.1:8545").strip()
        chain_id = int(os.environ.get("CHAIN_ID", "31337").strip())

        self.chain_id = chain_id
        self.w3 = Web3(Web3.HTTPProvider(rpc_url))

        if chain_id != 31337:
            try:
                from web3.middleware import ExtraDataToPOAMiddleware as poa_mw
            except ImportError:
                from web3.middleware import geth_poa_middleware as poa_mw
            self.w3.middleware_onion.inject(poa_mw, layer=0)

        if not self.w3.is_connected():
            raise ConnectionError(
                f"Failed to connect to blockchain node at {rpc_url}. "
                f"If using local mode, start the Hardhat node first:\n"
                f"  cd creditsense_ai/blockchain && npm run node"
            )

        # 2. Load Contract Address & Wallet Info
        env_addr = os.environ.get("CONTRACT_ADDRESS", "").strip()
        self.private_key = os.environ.get("WALLET_PRIVATE_KEY", "").strip()

        if not env_addr or not self.private_key:
            raise ValueError(
                "Missing Configuration: CONTRACT_ADDRESS or WALLET_PRIVATE_KEY is "
                "not defined in your .env file.\n"
                "Run the deploy script first:\n"
                "  cd creditsense_ai/blockchain && npm run deploy:local"
            )

        self.contract_address = self.w3.to_checksum_address(env_addr)
        self.account = self.w3.eth.account.from_key(self.private_key)

        # 3. Load ABI (auto-generated by Hardhat deploy script)
        abi_path = os.path.join(os.path.dirname(__file__), "contract_abi.json")
        try:
            with open(abi_path, "r") as f:
                self.contract_abi = json.load(f)
        except (FileNotFoundError, json.JSONDecodeError):
            raise FileNotFoundError(
                f"ABI file missing or empty at {abi_path}.\n"
                "Deploy the contract first to auto-generate it:\n"
                "  cd creditsense_ai/blockchain && npm run deploy:local"
            )

        self.contract = self.w3.eth.contract(
            address=self.contract_address, abi=self.contract_abi
        )

    def _send_transaction(self, func_call) -> str:
        """Internal Helper: Builds, signs, and dispatches the transaction."""
        nonce = self.w3.eth.get_transaction_count(self.account.address)

        try:
            gas_estimate = func_call.estimate_gas({"from": self.account.address})
        except Exception:
            gas_estimate = 500000

        # Use legacy gas pricing for local Hardhat, EIP-1559 for testnets
        tx_params = {
            "chainId": self.chain_id,
            "gas": int(gas_estimate * 1.5),
            "nonce": nonce,
        }

        if self.chain_id == 31337:
            # Local Hardhat — simple gas price
            tx_params["gasPrice"] = self.w3.to_wei("20", "gwei")
        else:
            # Remote testnet (e.g., Polygon Amoy) — EIP-1559
            tx_params["maxFeePerGas"] = self.w3.to_wei("35", "gwei")
            tx_params["maxPriorityFeePerGas"] = self.w3.to_wei("35", "gwei")

        tx = func_call.build_transaction(tx_params)

        signed_tx = self.w3.eth.account.sign_transaction(
            tx, private_key=self.private_key
        )

        raw_tx_payload = getattr(
            signed_tx,
            "raw_transaction",
            getattr(signed_tx, "rawTransaction", None),
        )

        tx_hash = self.w3.eth.send_raw_transaction(raw_tx_payload)
        return tx_hash.hex()

    def log_document(self, loan_id: str, doc_type: str, file_bytes: bytes) -> str:
        """
        Computes the SHA-256 footprint of the document and registers it immutably.
        Returns the finalized transaction hash string.
        """
        doc_hash = hashlib.sha256(file_bytes).digest()
        func_call = self.contract.functions.logDocument(loan_id, doc_type, doc_hash)

        tx_hash = self._send_transaction(func_call)
        self.w3.eth.wait_for_transaction_receipt(tx_hash)
        return tx_hash

    def log_action(
        self, loan_id: str, action_code: int, state_hash: bytes
    ) -> str:
        """
        Anchors the RL step payload using the compressed state hash.
        Returns the finalized transaction hash string.
        """
        func_call = self.contract.functions.logAction(
            loan_id, action_code, state_hash
        )
        tx_hash = self._send_transaction(func_call)
        self.w3.eth.wait_for_transaction_receipt(tx_hash)
        return tx_hash

    def log_decision(
        self, loan_id: str, decision: str, cam_file_bytes: bytes
    ) -> tuple[str, int]:

        cam_hash = hashlib.sha256(cam_file_bytes).digest()
        func_call = self.contract.functions.logDecision(loan_id, decision, cam_hash)

        tx_hash = self._send_transaction(func_call)
        receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash)
        return tx_hash, receipt.blockNumber

if __name__ == "__main__":
    print("Testing BlockchainLogger (local Hardhat node)...")
    try:
        logger = BlockchainLogger()
        print(f"✅ Connected! Wallet: {logger.account.address}")
        print(f"   Chain ID: {logger.chain_id}")

        balance = logger.w3.eth.get_balance(logger.account.address)
        print(f"   Balance: {logger.w3.from_wei(balance, 'ether')} ETH")

        print(f"\n⏳ Logging a mock GST document...")
        tx = logger.log_document("LOAN001", "gst", b"fake gst bytes")
        print(f"🥇 Success! TX Hash: {tx}")

        print(f"\n⏳ Logging an RL action...")
        state_hash = compress_state_to_hash([0.0] * 17)
        tx = logger.log_action("LOAN001", 5, state_hash)
        print(f"🥇 Success! TX Hash: {tx}")

        print(f"\n⏳ Logging a final decision...")
        tx, block = logger.log_decision("LOAN001", "APPROVE", b"cam_report_bytes")
        print(f"🥇 Success! TX Hash: {tx} | Block: {block}")

        print(f"\n✅ All blockchain operations verified on local node!")

    except Exception as e:
        print(f"⚠️ Test failed: {e}")
